spring.datasource.url=mysql://mufoaqpnvi5gbwe2:keuibq3xm7z4mb76@vlvlnl1grfzh34vj.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/k4zb9z8d04btllru?serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false



